#!/usr/bin/env bash
# Bulk import 63 tasks as GitHub Issues.
# Wymaga: gh CLI uwierzytelnione (gh auth login).
# Użycie: bash scripts/import_issues.sh [--dry-run]
set -euo pipefail

DRY_RUN=0
if [ "${1:-}" = "--dry-run" ]; then DRY_RUN=1; echo "(dry-run mode)"; fi

REPO="bialasqq/photo-ai-detector"
TASKS_DIR="$(dirname "$0")/../tasks"

create_issue() {
  local title="$1"; local body_file="$2"; local labels="$3"; local assignee="$4"
  if [ "$DRY_RUN" = "1" ]; then
    echo "[dry-run] gh issue create --title '$title' --label '$labels' --assignee '$assignee'"
    return
  fi
  gh issue create --repo "$REPO" --title "$title" --body-file "$body_file" --label "$labels" --assignee "$assignee"
  sleep 1  # GitHub rate limit courtesy
}

echo "Setup labels first (idempotent)..."
bash "$(dirname "$0")/setup_labels.sh" || true

echo "Creating: 0.1 — PRODUCT_SCOPE.md — must-have user stories + out-of-scope"
create_issue "[0.1] PRODUCT_SCOPE.md — must-have user stories + out-of-scope" "tasks/phase-0/0.1-product-scope-md-must-have-user-stories-out-of-scope.md" "P0,phase-0,owner-luq,docs,scope" "TODO-LUQ-GH-HANDLE"
echo "Creating: 0.2 — Zakup certyfikatu code signing Authenticode"
create_issue "[0.2] Zakup certyfikatu code signing Authenticode" "tasks/phase-0/0.2-zakup-certyfikatu-code-signing-authenticode.md" "P0,phase-0,owner-luq,release,security,blocker" "TODO-LUQ-GH-HANDLE"
echo "Creating: 0.3 — Setup .cursorrules w roocie repo"
create_issue "[0.3] Setup .cursorrules w roocie repo" "tasks/phase-0/0.3-setup-cursorrules-w-roocie-repo.md" "P0,phase-0,owner-grzesiek,setup,process" "bialasqq"
echo "Creating: 0.4 — TECH_DEBT.md — backlog 'nie naprawiać przy okazji'"
create_issue "[0.4] TECH_DEBT.md — backlog 'nie naprawiać przy okazji'" "tasks/phase-0/0.4-tech-debt-md-backlog-nie-naprawia-przy-okazji.md" "P0,phase-0,owner-grzesiek,docs,process" "bialasqq"
echo "Creating: 0.5 — GitHub Issues templates + Labels"
create_issue "[0.5] GitHub Issues templates + Labels" "tasks/phase-0/0.5-github-issues-templates-labels.md" "P0,phase-0,owner-grzesiek,devops,setup" "bialasqq"
echo "Creating: 1.1.1 — ai_core.py graceful error handling (DeepFace + DBSCAN)"
create_issue "[1.1.1] ai_core.py graceful error handling (DeepFace + DBSCAN)" "tasks/phase-1/1.1.1-ai-core-py-graceful-error-handling-deepface-dbscan.md" "P0,phase-1,owner-grzesiek,backend,stability" "bialasqq"
echo "Creating: 1.1.2 — Structured logging w %AppData% z rotacją"
create_issue "[1.1.2] Structured logging w %AppData% z rotacją" "tasks/phase-1/1.1.2-structured-logging-w-appdata-z-rotacj.md" "P0,phase-1,owner-grzesiek,backend,observability" "bialasqq"
echo "Creating: 1.1.3 — Standard error responses {error, code, hint}"
create_issue "[1.1.3] Standard error responses {error, code, hint}" "tasks/phase-1/1.1.3-standard-error-responses-error-code-hint.md" "P0,phase-1,owner-grzesiek,backend,api" "bialasqq"
echo "Creating: 1.1.4 — React Error Boundaries (App, Gallery, PeopleGrid)"
create_issue "[1.1.4] React Error Boundaries (App, Gallery, PeopleGrid)" "tasks/phase-1/1.1.4-react-error-boundaries-app-gallery-peoplegrid.md" "P0,phase-1,owner-luq,frontend,stability" "TODO-LUQ-GH-HANDLE"
echo "Creating: 1.2.1 — Gate /api/dev/* za PHOTO_ORGANIZER_DEV=1 [KRYTYCZNE]"
create_issue "[1.2.1] Gate /api/dev/* za PHOTO_ORGANIZER_DEV=1 [KRYTYCZNE]" "tasks/phase-1/1.2.1-gate-api-dev-za-photo-organizer-dev-1-krytyczne.md" "P0,phase-1,owner-grzesiek,backend,security,blocker" "bialasqq"
echo "Creating: 1.2.2 — Przenieś DB do %AppData%\com.photo.organizer\organizer.db [K"
create_issue "[1.2.2] Przenieś DB do %AppData%\com.photo.organizer\organizer.db [KRYTYCZNE]" "tasks/phase-1/1.2.2-przenie-db-do-appdata-com-photo-organizer-organizer-db-kryty.md" "P0,phase-1,owner-grzesiek,backend,tauri,data,blocker" "bialasqq"
echo "Creating: 1.2.3 — Path traversal validation w endpointach skanu"
create_issue "[1.2.3] Path traversal validation w endpointach skanu" "tasks/phase-1/1.2.3-path-traversal-validation-w-endpointach-skanu.md" "P0,phase-1,owner-luq,backend,security" "TODO-LUQ-GH-HANDLE"
echo "Creating: 1.2.4 — Wyłącz /docs i /redoc w release"
create_issue "[1.2.4] Wyłącz /docs i /redoc w release" "tasks/phase-1/1.2.4-wy-cz-docs-i-redoc-w-release.md" "P0,phase-1,owner-grzesiek,backend,security" "bialasqq"
echo "Creating: 1.2.5 — Bind tylko 127.0.0.1 + assert w starcie"
create_issue "[1.2.5] Bind tylko 127.0.0.1 + assert w starcie" "tasks/phase-1/1.2.5-bind-tylko-127-0-0-1-assert-w-starcie.md" "P0,phase-1,owner-grzesiek,backend,security" "bialasqq"
echo "Creating: 1.3.1 — DB indeksy: faces(person_id), photos(processed, has_faces)"
create_issue "[1.3.1] DB indeksy: faces(person_id), photos(processed, has_faces)" "tasks/phase-1/1.3.1-db-indeksy-faces-person-id-photos-processed-has-faces.md" "P0,phase-1,owner-luq,backend,database,performance" "TODO-LUQ-GH-HANDLE"
echo "Creating: 1.3.2 — Schema versioning + numbered SQL migrations (no Alembic)"
create_issue "[1.3.2] Schema versioning + numbered SQL migrations (no Alembic)" "tasks/phase-1/1.3.2-schema-versioning-numbered-sql-migrations-no-alembic.md" "P0,phase-1,owner-grzesiek,backend,database" "bialasqq"
echo "Creating: 1.3.3 — Batch inserts (50-100) w transakcji"
create_issue "[1.3.3] Batch inserts (50-100) w transakcji" "tasks/phase-1/1.3.3-batch-inserts-50-100-w-transakcji.md" "P0,phase-1,owner-grzesiek,backend,database,performance" "bialasqq"
echo "Creating: 1.3.4 — PRAGMA foreign_keys=ON + integrity_check przy starcie"
create_issue "[1.3.4] PRAGMA foreign_keys=ON + integrity_check przy starcie" "tasks/phase-1/1.3.4-pragma-foreign-keys-on-integrity-check-przy-starcie.md" "P0,phase-1,owner-luq,backend,database" "TODO-LUQ-GH-HANDLE"
echo "Creating: 1.4.1 — /api/v1/ prefix dla nowych endpointów"
create_issue "[1.4.1] /api/v1/ prefix dla nowych endpointów" "tasks/phase-1/1.4.1-api-v1-prefix-dla-nowych-endpoint-w.md" "P1,phase-1,owner-grzesiek,backend,api" "bialasqq"
echo "Creating: 1.4.2 — Pydantic v2 validators na wszystkich POST"
create_issue "[1.4.2] Pydantic v2 validators na wszystkich POST" "tasks/phase-1/1.4.2-pydantic-v2-validators-na-wszystkich-post.md" "P0,phase-1,owner-grzesiek,backend,api,security" "bialasqq"
echo "Creating: 1.4.3 — Scan cancellation: POST /api/v1/scan-cancel + UI button"
create_issue "[1.4.3] Scan cancellation: POST /api/v1/scan-cancel + UI button" "tasks/phase-1/1.4.3-scan-cancellation-post-api-v1-scan-cancel-ui-button.md" "P0,phase-1,owner-luq,backend,frontend,ux" "TODO-LUQ-GH-HANDLE"
echo "Creating: 2.0.1 — Benchmark baseline: skan 1k/5k/10k zdjęć [PRZED FAISS]"
create_issue "[2.0.1] Benchmark baseline: skan 1k/5k/10k zdjęć [PRZED FAISS]" "tasks/phase-2/2.0.1-benchmark-baseline-skan-1k-5k-10k-zdj-przed-faiss.md" "P0,phase-2,owner-luq,performance,tests" "TODO-LUQ-GH-HANDLE"
echo "Creating: 2.0.2 — docs/BENCHMARKS.md + scripts/benchmark.py w repo"
create_issue "[2.0.2] docs/BENCHMARKS.md + scripts/benchmark.py w repo" "tasks/phase-2/2.0.2-docs-benchmarks-md-scripts-benchmark-py-w-repo.md" "P0,phase-2,owner-grzesiek,performance,docs" "bialasqq"
echo "Creating: 2.1.1 — Batch detection 32 obrazów w ai_core"
create_issue "[2.1.1] Batch detection 32 obrazów w ai_core" "tasks/phase-2/2.1.1-batch-detection-32-obraz-w-w-ai-core.md" "P0,phase-2,owner-grzesiek,backend,ml,performance" "bialasqq"
echo "Creating: 2.1.2 — Async I/O dla load obrazów (PIL) + decouple od inference"
create_issue "[2.1.2] Async I/O dla load obrazów (PIL) + decouple od inference" "tasks/phase-2/2.1.2-async-i-o-dla-load-obraz-w-pil-decouple-od-inference.md" "P1,phase-2,owner-grzesiek,backend,performance" "bialasqq"
echo "Creating: 2.1.3 — GPU detection (CUDA) za flagą + graceful fallback"
create_issue "[2.1.3] GPU detection (CUDA) za flagą + graceful fallback" "tasks/phase-2/2.1.3-gpu-detection-cuda-za-flag-graceful-fallback.md" "P1,phase-2,owner-luq,backend,ml,performance" "TODO-LUQ-GH-HANDLE"
echo "Creating: 2.1.4 — /api/v1/progress — fazy (scan/embed/cluster) + ETA"
create_issue "[2.1.4] /api/v1/progress — fazy (scan/embed/cluster) + ETA" "tasks/phase-2/2.1.4-api-v1-progress-fazy-scan-embed-cluster-eta.md" "P1,phase-2,owner-grzesiek,backend,frontend,ux" "bialasqq"
echo "Creating: 2.1.5 — Cancellation tokens w batch loop (wzmocnienie 1.4.3)"
create_issue "[2.1.5] Cancellation tokens w batch loop (wzmocnienie 1.4.3)" "tasks/phase-2/2.1.5-cancellation-tokens-w-batch-loop-wzmocnienie-1-4-3.md" "P1,phase-2,owner-grzesiek,backend,performance" "bialasqq"
echo "Creating: 2.2.1 — FAISS integration: IndexFlatIP + persist w AppData"
create_issue "[2.2.1] FAISS integration: IndexFlatIP + persist w AppData" "tasks/phase-2/2.2.1-faiss-integration-indexflatip-persist-w-appdata.md" "P0,phase-2,owner-grzesiek,backend,ml,performance" "bialasqq"
echo "Creating: 2.2.2 — Incremental clustering: FAISS top-k → assign or new"
create_issue "[2.2.2] Incremental clustering: FAISS top-k → assign or new" "tasks/phase-2/2.2.2-incremental-clustering-faiss-top-k-assign-or-new.md" "P0,phase-2,owner-luq,backend,ml" "TODO-LUQ-GH-HANDLE"
echo "Creating: 2.2.3 — Silhouette / Davies-Bouldin score po re-clusteringu"
create_issue "[2.2.3] Silhouette / Davies-Bouldin score po re-clusteringu" "tasks/phase-2/2.2.3-silhouette-davies-bouldin-score-po-re-clusteringu.md" "P1,phase-2,owner-luq,backend,ml" "TODO-LUQ-GH-HANDLE"
echo "Creating: 2.2.4 — Auto-tune eps, min_samples (grid search)"
create_issue "[2.2.4] Auto-tune eps, min_samples (grid search)" "tasks/phase-2/2.2.4-auto-tune-eps-min-samples-grid-search.md" "P2,phase-2,owner-grzesiek,backend,ml" "bialasqq"
echo "Creating: 2.3.1 — react-window w Gallery przy >200 zdjęć"
create_issue "[2.3.1] react-window w Gallery przy >200 zdjęć" "tasks/phase-2/2.3.1-react-window-w-gallery-przy-200-zdj.md" "P0,phase-2,owner-luq,frontend,performance" "TODO-LUQ-GH-HANDLE"
echo "Creating: 2.3.2 — IntersectionObserver lazy load miniaturek"
create_issue "[2.3.2] IntersectionObserver lazy load miniaturek" "tasks/phase-2/2.3.2-intersectionobserver-lazy-load-miniaturek.md" "P0,phase-2,owner-luq,frontend,performance" "TODO-LUQ-GH-HANDLE"
echo "Creating: 2.3.3 — Cache miniaturek LRU eviction (limit 500 MB w AppData)"
create_issue "[2.3.3] Cache miniaturek LRU eviction (limit 500 MB w AppData)" "tasks/phase-2/2.3.3-cache-miniaturek-lru-eviction-limit-500-mb-w-appdata.md" "P1,phase-2,owner-grzesiek,backend,performance" "bialasqq"
echo "Creating: 3.1.1 — OWASP ASVS L1 self-audit"
create_issue "[3.1.1] OWASP ASVS L1 self-audit" "tasks/phase-3/3.1.1-owasp-asvs-l1-self-audit.md" "P0,phase-3,owner-luq,security,audit" "TODO-LUQ-GH-HANDLE"
echo "Creating: 3.1.2 — DNS rebinding mitigation (Host header check)"
create_issue "[3.1.2] DNS rebinding mitigation (Host header check)" "tasks/phase-3/3.1.2-dns-rebinding-mitigation-host-header-check.md" "P1,phase-3,owner-luq,backend,security" "TODO-LUQ-GH-HANDLE"
echo "Creating: 3.1.3 — Security headers (CSP w Tauri webview, X-Content-Type-Option"
create_issue "[3.1.3] Security headers (CSP w Tauri webview, X-Content-Type-Options)" "tasks/phase-3/3.1.3-security-headers-csp-w-tauri-webview-x-content-type-options.md" "P1,phase-3,owner-grzesiek,backend,tauri,security" "bialasqq"
echo "Creating: 3.1.4 — Path validation hardening + symlink rejection"
create_issue "[3.1.4] Path validation hardening + symlink rejection" "tasks/phase-3/3.1.4-path-validation-hardening-symlink-rejection.md" "P0,phase-3,owner-luq,backend,security" "TODO-LUQ-GH-HANDLE"
echo "Creating: 3.1.5 — pip-audit + npm audit w CI (warning only)"
create_issue "[3.1.5] pip-audit + npm audit w CI (warning only)" "tasks/phase-3/3.1.5-pip-audit-npm-audit-w-ci-warning-only.md" "P1,phase-3,owner-grzesiek,devops,security" "bialasqq"
echo "Creating: 3.2.1 — Unit tests Python: 80%+ coverage na database/main/ai_core"
create_issue "[3.2.1] Unit tests Python: 80%+ coverage na database/main/ai_core" "tasks/phase-3/3.2.1-unit-tests-python-80-coverage-na-database-main-ai-core.md" "P0,phase-3,owner-luq,tests,quality" "TODO-LUQ-GH-HANDLE"
echo "Creating: 3.2.2 — Integration tests: FastAPI TestClient dla każdego endpointu"
create_issue "[3.2.2] Integration tests: FastAPI TestClient dla każdego endpointu" "tasks/phase-3/3.2.2-integration-tests-fastapi-testclient-dla-ka-dego-endpointu.md" "P0,phase-3,owner-luq,tests,quality" "TODO-LUQ-GH-HANDLE"
echo "Creating: 3.2.3 — E2E tests: Playwright na Tauri webview"
create_issue "[3.2.3] E2E tests: Playwright na Tauri webview" "tasks/phase-3/3.2.3-e2e-tests-playwright-na-tauri-webview.md" "P1,phase-3,owner-luq,tests,e2e" "TODO-LUQ-GH-HANDLE"
echo "Creating: 3.2.4 — Benchmarks jako pytest-benchmark, fail na regresji >20%"
create_issue "[3.2.4] Benchmarks jako pytest-benchmark, fail na regresji >20%" "tasks/phase-3/3.2.4-benchmarks-jako-pytest-benchmark-fail-na-regresji-20.md" "P1,phase-3,owner-grzesiek,tests,performance,devops" "bialasqq"
echo "Creating: 3.2.5 — GitHub Actions ci.yml (pytest + npm build + lint)"
create_issue "[3.2.5] GitHub Actions ci.yml (pytest + npm build + lint)" "tasks/phase-3/3.2.5-github-actions-ci-yml-pytest-npm-build-lint.md" "P0,phase-3,owner-grzesiek,devops,quality,blocker" "bialasqq"
echo "Creating: 3.2.6 — Vitest: FaceCropImage, Gallery filters, PeopleGrid"
create_issue "[3.2.6] Vitest: FaceCropImage, Gallery filters, PeopleGrid" "tasks/phase-3/3.2.6-vitest-facecropimage-gallery-filters-peoplegrid.md" "P0,phase-3,owner-luq,frontend,tests" "TODO-LUQ-GH-HANDLE"
echo "Creating: 3.3.1 — README sekcja Production Install + Building from Source"
create_issue "[3.3.1] README sekcja Production Install + Building from Source" "tasks/phase-3/3.3.1-readme-sekcja-production-install-building-from-source.md" "P0,phase-3,owner-luq,docs" "TODO-LUQ-GH-HANDLE"
echo "Creating: 3.3.2 — docs/ARCHITECTURE.md + Mermaid diagram"
create_issue "[3.3.2] docs/ARCHITECTURE.md + Mermaid diagram" "tasks/phase-3/3.3.2-docs-architecture-md-mermaid-diagram.md" "P0,phase-3,owner-luq,docs" "TODO-LUQ-GH-HANDLE"
echo "Creating: 3.3.3 — docs/USER_GUIDE.md ze screenshotami"
create_issue "[3.3.3] docs/USER_GUIDE.md ze screenshotami" "tasks/phase-3/3.3.3-docs-user-guide-md-ze-screenshotami.md" "P0,phase-3,owner-luq,docs" "TODO-LUQ-GH-HANDLE"
echo "Creating: 4.1.1 — Tauri updater plugin + signed GitHub Releases feed"
create_issue "[4.1.1] Tauri updater plugin + signed GitHub Releases feed" "tasks/phase-4/4.1.1-tauri-updater-plugin-signed-github-releases-feed.md" "P1,phase-4,owner-grzesiek,release,tauri" "bialasqq"
echo "Creating: 4.1.2 — Code signing MSI Authenticode [BLOCKER]"
create_issue "[4.1.2] Code signing MSI Authenticode [BLOCKER]" "tasks/phase-4/4.1.2-code-signing-msi-authenticode-blocker.md" "P0,phase-4,owner-luq,release,security,blocker" "TODO-LUQ-GH-HANDLE"
echo "Creating: 4.1.4 — Release workflow: tag v* → build → sign → upload"
create_issue "[4.1.4] Release workflow: tag v* → build → sign → upload" "tasks/phase-4/4.1.4-release-workflow-tag-v-build-sign-upload.md" "P0,phase-4,owner-grzesiek,release,devops" "bialasqq"
echo "Creating: 4.1.5 — Splash screen 'Loading AI models...' (cold start)"
create_issue "[4.1.5] Splash screen 'Loading AI models...' (cold start)" "tasks/phase-4/4.1.5-splash-screen-loading-ai-models-cold-start.md" "P0,phase-4,owner-luq,frontend,ux" "TODO-LUQ-GH-HANDLE"
echo "Creating: 4.2.1 — Sentry integration, DEFAULT OFF, opt-in w Settings"
create_issue "[4.2.1] Sentry integration, DEFAULT OFF, opt-in w Settings" "tasks/phase-4/4.2.1-sentry-integration-default-off-opt-in-w-settings.md" "P1,phase-4,owner-grzesiek,backend,frontend,observability" "bialasqq"
echo "Creating: 4.2.2 — /api/v1/health rozszerzony (db_ok, model_loaded, schema_vers"
create_issue "[4.2.2] /api/v1/health rozszerzony (db_ok, model_loaded, schema_version, disk_free)" "tasks/phase-4/4.2.2-api-v1-health-rozszerzony-db-ok-model-loaded-schema-version.md" "P0,phase-4,owner-grzesiek,backend,observability" "bialasqq"
echo "Creating: 4.2.3 — Help → 'Copy diagnostics' do schowka"
create_issue "[4.2.3] Help → 'Copy diagnostics' do schowka" "tasks/phase-4/4.2.3-help-copy-diagnostics-do-schowka.md" "P0,phase-4,owner-luq,frontend,backend,support" "TODO-LUQ-GH-HANDLE"
echo "Creating: 4.3.1 — Backup feature: Help → Export library → ZIP"
create_issue "[4.3.1] Backup feature: Help → Export library → ZIP" "tasks/phase-4/4.3.1-backup-feature-help-export-library-zip.md" "P0,phase-4,owner-luq,backend,frontend,feature" "TODO-LUQ-GH-HANDLE"
echo "Creating: 4.3.2 — Data retention: cleanup cache miniaturek >90 dni"
create_issue "[4.3.2] Data retention: cleanup cache miniaturek >90 dni" "tasks/phase-4/4.3.2-data-retention-cleanup-cache-miniaturek-90-dni.md" "P1,phase-4,owner-grzesiek,backend,maintenance" "bialasqq"
echo "Creating: 4.3.3 — Migration system smoke test (1.0 → 1.1 mock schema bump)"
create_issue "[4.3.3] Migration system smoke test (1.0 → 1.1 mock schema bump)" "tasks/phase-4/4.3.3-migration-system-smoke-test-1-0-1-1-mock-schema-bump.md" "P0,phase-4,owner-grzesiek,backend,database,release" "bialasqq"
echo "Creating: 4.4.1 — CHANGELOG.md + LICENSE"
create_issue "[4.4.1] CHANGELOG.md + LICENSE" "tasks/phase-4/4.4.1-changelog-md-license.md" "P0,phase-4,owner-luq,docs,release" "TODO-LUQ-GH-HANDLE"
echo "Creating: 4.4.2 — THIRD_PARTY_NOTICES.md (TF, DeepFace, OpenCV, ArcFace, FAISS"
create_issue "[4.4.2] THIRD_PARTY_NOTICES.md (TF, DeepFace, OpenCV, ArcFace, FAISS)" "tasks/phase-4/4.4.2-third-party-notices-md-tf-deepface-opencv-arcface-faiss.md" "P0,phase-4,owner-luq,docs,compliance,release" "TODO-LUQ-GH-HANDLE"
echo "Creating: 4.4.3 — SECURITY.md (responsible disclosure)"
create_issue "[4.4.3] SECURITY.md (responsible disclosure)" "tasks/phase-4/4.4.3-security-md-responsible-disclosure.md" "P0,phase-4,owner-luq,docs,security,release" "TODO-LUQ-GH-HANDLE"
echo "Creating: 4.5.1 — Release VM Test [RELEASE GATE]"
create_issue "[4.5.1] Release VM Test [RELEASE GATE]" "tasks/phase-4/4.5.1-release-vm-test-release-gate.md" "P0,phase-4,owner-luq,release,qa,blocker" "TODO-LUQ-GH-HANDLE"

echo "Done. Sprawdź https://github.com/$REPO/issues"